[2025-10-08T04:25:54.599+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-08T04:25:54.639+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_analytics.run_spark_stream manual__2025-10-08T04:20:14.712439+00:00 [queued]>
[2025-10-08T04:25:54.650+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_analytics.run_spark_stream manual__2025-10-08T04:20:14.712439+00:00 [queued]>
[2025-10-08T04:25:54.655+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-08T04:25:54.678+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_stream> on 2025-10-08 04:20:14.712439+00:00
[2025-10-08T04:25:54.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=261) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-08T04:25:54.692+0000] {standard_task_runner.py:64} INFO - Started process 266 to run task
[2025-10-08T04:25:54.692+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'restaurant_analytics', 'run_spark_stream', 'manual__2025-10-08T04:20:14.712439+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_dag.py', '--cfg-path', '/tmp/tmp4u6faoky']
[2025-10-08T04:25:54.697+0000] {standard_task_runner.py:91} INFO - Job 119: Subtask run_spark_stream
[2025-10-08T04:25:54.804+0000] {task_command.py:426} INFO - Running <TaskInstance: restaurant_analytics.run_spark_stream manual__2025-10-08T04:20:14.712439+00:00 [running]> on host c34aac175a74
[2025-10-08T04:25:54.971+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='quantruong1918@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='restaurant_analytics' AIRFLOW_CTX_TASK_ID='run_spark_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T04:20:14.712439+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-08T04:20:14.712439+00:00'
[2025-10-08T04:25:54.975+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-08T04:25:54.977+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-08T04:25:54.979+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/spark/bin/spark-submit --master local[*] /opt/***/dags/spark_streaming.py']
[2025-10-08T04:25:54.999+0000] {subprocess.py:86} INFO - Output:
[2025-10-08T04:26:01.386+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-08T04:26:01.387+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/spark_streaming.py", line 5, in <module>
[2025-10-08T04:26:01.392+0000] {subprocess.py:93} INFO -     from pyspark.ml import PipelineModel
[2025-10-08T04:26:01.393+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/__init__.py", line 22, in <module>
[2025-10-08T04:26:01.394+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 40, in <module>
[2025-10-08T04:26:01.395+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 32, in <module>
[2025-10-08T04:26:01.395+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'numpy'
[2025-10-08T04:26:01.465+0000] {subprocess.py:93} INFO - 25/10/08 04:26:01 INFO ShutdownHookManager: Shutdown hook called
[2025-10-08T04:26:01.473+0000] {subprocess.py:93} INFO - 25/10/08 04:26:01 INFO ShutdownHookManager: Deleting directory /tmp/spark-20ea2959-b0ad-4fb8-8d26-212ad0f94136
[2025-10-08T04:26:01.532+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-08T04:26:01.534+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-08T04:26:01.554+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-08T04:26:01.564+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=restaurant_analytics, task_id=run_spark_stream, run_id=manual__2025-10-08T04:20:14.712439+00:00, execution_date=20251008T042014, start_date=20251008T042554, end_date=20251008T042601
[2025-10-08T04:26:01.592+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 119 for task run_spark_stream (Bash command failed. The command returned a non-zero exit code 1.; 266)
[2025-10-08T04:26:01.621+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-08T04:26:01.646+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-08T04:26:01.649+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
