[2025-10-08T06:00:57.287+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-08T06:00:57.341+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restaurant_analytics.run_spark_stream manual__2025-10-08T05:55:16.777072+00:00 [queued]>
[2025-10-08T06:00:57.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restaurant_analytics.run_spark_stream manual__2025-10-08T05:55:16.777072+00:00 [queued]>
[2025-10-08T06:00:57.370+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-10-08T06:00:57.400+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_spark_stream> on 2025-10-08 05:55:16.777072+00:00
[2025-10-08T06:00:57.417+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=413) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-08T06:00:57.422+0000] {standard_task_runner.py:64} INFO - Started process 417 to run task
[2025-10-08T06:00:57.422+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'restaurant_analytics', 'run_spark_stream', 'manual__2025-10-08T05:55:16.777072+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/restaurant_dag.py', '--cfg-path', '/tmp/tmp6av51r_x']
[2025-10-08T06:00:57.427+0000] {standard_task_runner.py:91} INFO - Job 149: Subtask run_spark_stream
[2025-10-08T06:00:57.579+0000] {task_command.py:426} INFO - Running <TaskInstance: restaurant_analytics.run_spark_stream manual__2025-10-08T05:55:16.777072+00:00 [running]> on host c34aac175a74
[2025-10-08T06:00:57.822+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='quantruong1918@gmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='restaurant_analytics' AIRFLOW_CTX_TASK_ID='run_spark_stream' AIRFLOW_CTX_EXECUTION_DATE='2025-10-08T05:55:16.777072+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-08T05:55:16.777072+00:00'
[2025-10-08T06:00:57.829+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-08T06:00:57.832+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-08T06:00:57.834+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/opt/spark/bin/spark-submit --master local[*] /opt/***/dags/spark_streaming.py']
[2025-10-08T06:00:57.863+0000] {subprocess.py:86} INFO - Output:
[2025-10-08T06:01:04.937+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-10-08T06:01:04.938+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/spark_streaming.py", line 5, in <module>
[2025-10-08T06:01:04.941+0000] {subprocess.py:93} INFO -     from pyspark.ml import PipelineModel
[2025-10-08T06:01:04.942+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/__init__.py", line 22, in <module>
[2025-10-08T06:01:04.943+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/base.py", line 40, in <module>
[2025-10-08T06:01:04.944+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 32, in <module>
[2025-10-08T06:01:04.945+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'numpy'
[2025-10-08T06:01:05.016+0000] {subprocess.py:93} INFO - 25/10/08 06:01:05 INFO ShutdownHookManager: Shutdown hook called
[2025-10-08T06:01:05.025+0000] {subprocess.py:93} INFO - 25/10/08 06:01:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-e6f723b8-dc52-4e27-9ddd-a8339afd26c4
[2025-10-08T06:01:05.092+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-08T06:01:05.094+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-08T06:01:05.117+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-08T06:01:05.132+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=restaurant_analytics, task_id=run_spark_stream, run_id=manual__2025-10-08T05:55:16.777072+00:00, execution_date=20251008T055516, start_date=20251008T060057, end_date=20251008T060105
[2025-10-08T06:01:05.180+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 149 for task run_spark_stream (Bash command failed. The command returned a non-zero exit code 1.; 417)
[2025-10-08T06:01:05.244+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-10-08T06:01:05.293+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-08T06:01:05.299+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
